var annotated_dup =
[
    [ "std", "namespacestd.html", [
      [ "initializer_list", "classstd_1_1initializer__list.html", "classstd_1_1initializer__list" ]
    ] ],
    [ "VLCB", "namespace_v_l_c_b.html", [
      [ "AbstractEventTeachingService", "class_v_l_c_b_1_1_abstract_event_teaching_service.html", "class_v_l_c_b_1_1_abstract_event_teaching_service" ],
      [ "ArrayHolder", "class_v_l_c_b_1_1_array_holder.html", "class_v_l_c_b_1_1_array_holder" ],
      [ "CAN2515", "class_v_l_c_b_1_1_c_a_n2515.html", "class_v_l_c_b_1_1_c_a_n2515" ],
      [ "CanService", "class_v_l_c_b_1_1_can_service.html", "class_v_l_c_b_1_1_can_service" ],
      [ "CanServiceWithDiagnostics", "class_v_l_c_b_1_1_can_service_with_diagnostics.html", "class_v_l_c_b_1_1_can_service_with_diagnostics" ],
      [ "CANFrame", "struct_v_l_c_b_1_1_c_a_n_frame.html", "struct_v_l_c_b_1_1_c_a_n_frame" ],
      [ "CanTransport", "class_v_l_c_b_1_1_can_transport.html", "class_v_l_c_b_1_1_can_transport" ],
      [ "CircularBuffer", "class_v_l_c_b_1_1_circular_buffer.html", "class_v_l_c_b_1_1_circular_buffer" ],
      [ "Configuration", "class_v_l_c_b_1_1_configuration.html", "class_v_l_c_b_1_1_configuration" ],
      [ "ConsumeOwnEventsService", "class_v_l_c_b_1_1_consume_own_events_service.html", "class_v_l_c_b_1_1_consume_own_events_service" ],
      [ "VlcbMessage", "struct_v_l_c_b_1_1_vlcb_message.html", "struct_v_l_c_b_1_1_vlcb_message" ],
      [ "Action", "struct_v_l_c_b_1_1_action.html", "struct_v_l_c_b_1_1_action" ],
      [ "Controller", "class_v_l_c_b_1_1_controller.html", "class_v_l_c_b_1_1_controller" ],
      [ "DueEepromEmulationStorage", "class_v_l_c_b_1_1_due_eeprom_emulation_storage.html", "class_v_l_c_b_1_1_due_eeprom_emulation_storage" ],
      [ "EepromExternalStorage", "class_v_l_c_b_1_1_eeprom_external_storage.html", "class_v_l_c_b_1_1_eeprom_external_storage" ],
      [ "EepromInternalStorage", "class_v_l_c_b_1_1_eeprom_internal_storage.html", "class_v_l_c_b_1_1_eeprom_internal_storage" ],
      [ "EventConsumerService", "class_v_l_c_b_1_1_event_consumer_service.html", "class_v_l_c_b_1_1_event_consumer_service" ],
      [ "EventConsumerServiceWithDiagnostics", "class_v_l_c_b_1_1_event_consumer_service_with_diagnostics.html", "class_v_l_c_b_1_1_event_consumer_service_with_diagnostics" ],
      [ "EventProducerService", "class_v_l_c_b_1_1_event_producer_service.html", "class_v_l_c_b_1_1_event_producer_service" ],
      [ "EventProducerServiceWithDiagnostics", "class_v_l_c_b_1_1_event_producer_service_with_diagnostics.html", "class_v_l_c_b_1_1_event_producer_service_with_diagnostics" ],
      [ "EventSlotTeachingService", "class_v_l_c_b_1_1_event_slot_teaching_service.html", "class_v_l_c_b_1_1_event_slot_teaching_service" ],
      [ "EventTeachingService", "class_v_l_c_b_1_1_event_teaching_service.html", null ],
      [ "EventTeachingServiceWithDiagnostics", "class_v_l_c_b_1_1_event_teaching_service_with_diagnostics.html", "class_v_l_c_b_1_1_event_teaching_service_with_diagnostics" ],
      [ "flash_page_t", "struct_v_l_c_b_1_1flash__page__t.html", "struct_v_l_c_b_1_1flash__page__t" ],
      [ "FlashStorage", "class_v_l_c_b_1_1_flash_storage.html", "class_v_l_c_b_1_1_flash_storage" ],
      [ "LED", "class_v_l_c_b_1_1_l_e_d.html", "class_v_l_c_b_1_1_l_e_d" ],
      [ "LEDUserInterface", "class_v_l_c_b_1_1_l_e_d_user_interface.html", "class_v_l_c_b_1_1_l_e_d_user_interface" ],
      [ "LongMessageService", "class_v_l_c_b_1_1_long_message_service.html", "class_v_l_c_b_1_1_long_message_service" ],
      [ "receive_context_t", "struct_v_l_c_b_1_1receive__context__t.html", "struct_v_l_c_b_1_1receive__context__t" ],
      [ "send_context_t", "struct_v_l_c_b_1_1send__context__t.html", "struct_v_l_c_b_1_1send__context__t" ],
      [ "LongMessageServiceEx", "class_v_l_c_b_1_1_long_message_service_ex.html", "class_v_l_c_b_1_1_long_message_service_ex" ],
      [ "MinimumNodeService", "class_v_l_c_b_1_1_minimum_node_service.html", "class_v_l_c_b_1_1_minimum_node_service" ],
      [ "MinimumNodeServiceWithDiagnostics", "class_v_l_c_b_1_1_minimum_node_service_with_diagnostics.html", "class_v_l_c_b_1_1_minimum_node_service_with_diagnostics" ],
      [ "NodeVariableService", "class_v_l_c_b_1_1_node_variable_service.html", "class_v_l_c_b_1_1_node_variable_service" ],
      [ "Parameters", "class_v_l_c_b_1_1_parameters.html", "class_v_l_c_b_1_1_parameters" ],
      [ "SerialGC", "class_v_l_c_b_1_1_serial_g_c.html", "class_v_l_c_b_1_1_serial_g_c" ],
      [ "SerialUserInterface", "class_v_l_c_b_1_1_serial_user_interface.html", "class_v_l_c_b_1_1_serial_user_interface" ],
      [ "Service", "class_v_l_c_b_1_1_service.html", null ],
      [ "Storage", "class_v_l_c_b_1_1_storage.html", "class_v_l_c_b_1_1_storage" ],
      [ "Switch", "class_v_l_c_b_1_1_switch.html", "class_v_l_c_b_1_1_switch" ],
      [ "Transport", "class_v_l_c_b_1_1_transport.html", "class_v_l_c_b_1_1_transport" ]
    ] ]
];